services:
    pgsql:
        container_name: flashcards_pgsql
        image: "postgres:16.3-alpine3.20"
        restart: unless-stopped
        volumes:
          - ./pgsql_data:/var/lib/postgresql/data
        environment:
          POSTGRES_USER: ${DATABASE_USER}
          POSTGRES_PASSWORD: ${DATABASE_PASS}
          POSTGRES_DB: ${DATABASE_NAME}
          PGDATA: /var/lib/postgresql/data/pgdata

    golang:
      container_name: flashcards_golang
      image: "golang:1.22.7-alpine3.20"
      restart: unless-stopped
      env_file:
        - ./.env
      ports:
        - ${GOLANG_EXPOSE_PORT}:${GOLANG_SERVER_PORT}
      working_dir: /app
      volumes:
        - .:/app
      command: sh -c "go build -o ./app && ./app"