services:
  backend_builder:
    image: nodejs
    container_name: ${COMPOSE_PROJECT_NAME}_backend_builder
    restart: unless-stopped
    build:
      context: ./../../
      dockerfile: ./environment/local/Dockerfile
    volumes:
      - ./../../:/app
    entrypoint: /entrypoint-backend.sh .
    ports:
    - 3000:3000

  node:
    image: nodejs
    container_name: ${COMPOSE_PROJECT_NAME}_node
    build:
      context: ./../../
      dockerfile: ./environment/local/Dockerfile
    volumes:
      - ./../../:/app
    networks:
      - flashcards_network

  backend-db:
    image: postgres:13
    container_name: ${COMPOSE_PROJECT_NAME}_pgsql
    restart: unless-stopped
    networks:
      - flashcards_network
    ports:
      - 5432:5432
    volumes:
      - pgsql_cache:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "flashcards"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"

networks:
  flashcards_network:

volumes:
  frontend_dist_volume:
  pgsql_cache:
